### ISSUE TITLE
What does it take to enable pasting images from the clipboard?

### ISSUE THREAD

**Issue by linucksrox** [madodig/wikijs-customization#8]
One of the main drawbacks of the current version is that I can't paste images from the clipboard. This is a problem that has been solved in many other projects, but a lot of the systems out there today still don't allow pasting images directly from the clipboard. Do you know how much work it would be to implement this?

**Comment by madodig** [comment]
This code parses the HTML/CSS code and changes it on-the-fly. It isn't possible to implement such a feature by this approach, since the injected code isn't loaded in editor by Wiki.JS design.

Wiki.JS has a feedback site where users can ask for features and this feature has already been asked for ([ability-to-paste-images-into-md-editor](https://js.wiki/feedback/p/ability-to-paste-images-into-md-editor)). As of this writing, it has 466 upvotes and is planned, so it might be a part of a future release (v3).

You can also join the [Wiki.JS Slack channel](https://wiki.requarks.io/slack) and ask there if and when the feature will be introduced.

**Comment by linucksrox** [comment]
Thanks for the quick update! That makes sense that you can't use the injection approach for this purpose. I have already voted on that feature, but I'm just having a hard time waiting for version 3 I guess. I think this project is going to explode in popularity when that gets released.
